[package]
name = "basic-impl"
version = "0.1.1"
edition = "2021"


[dependencies]
ext-server = { path = ".." }
rocket = "0.5.1"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }